### ISSUE TITLE
How do I manually display a popup?

### ISSUE THREAD

**Issue by valh1996** [indoorequal/vue-maplibre-gl#102]
Hi,

I've tried using a [`ref`](https://vuejs.org/guide/essentials/template-refs#template-refs) on my popups to show them but only the `remove` method is [exposed](https://github.com/indoorequal/vue-maplibre-gl/blob/master/lib/components/popup.component.ts#L155-L159).

So, is there a simple way to toggle a popup manually from the code according to a certain user action?

Thanks!

**Comment by francois2metz** [comment]
Hi,

Thanks for reporting this issue. 
You can use a standard `v-if` to display/hide your popup. 

Hope it helps.

**Comment by francois2metz** [comment]
Hi,

I'm not sure to understand your problem. You can have the state you want.

**Comment by valh1996** [comment]
My bad, I had buggy code that unexpectedly reset the state which still hide it... ! I apologize for the inconvenience
