### ISSUE TITLE
 issue with right ot left languages ( mapbox-gl-rtl-text)

### ISSUE THREAD

**Issue by yassine-mahjoubi** [indoorequal/vue-maplibre-gl#103]
Hi, is there a proper way to intergrate this plugin (  [mapbox-gl-rtl-text ](https://github.com/mapbox/mapbox-gl-rtl-text)) it fixes the names in rtl languages  ?

**Comment by francois2metz** [comment]
Hi,

Not sure if the plkugin rtl-text is maintained and is working with maplibre. You can always require the maplibre library and do what you want with it.

**Comment by francois2metz** [comment]
Closing. If you have more questions, feel free to reopen.
