### ISSUE TITLE
Can't run in Client Side Vue component using Astro

### ISSUE THREAD

**Issue by jtbaker** [indoorequal/vue-maplibre-gl#34]
Seems to be some issues with how the module and some of its dependencies are bundled, being a combination of UMD/CJS.

Reproducible example here: https://stackblitz.com/edit/astro-vue-maplibre-gl?file=src%2Fcomponents%2FApp.vue

Using

```
import { MglMap } from '@indoorequal/vue-maplibre-gl';
```
yields
```Error: Cannot read properties of undefined (reading 'reactive')```

while
```
import { MglMap } from '@indoorequal/vue-maplibre-gl/dist/vue-maplibre-gl.es.js';
```
yields
```Named export 'LngLat' not found. The requested module 'maplibre-gl' is a CommonJS module, which may not support all module.exports as named exports.```

I tried various permutations on this, including importing directly from the typescript lib files like `@indoorequal/vue-maplibre-gl/lib/components/map.component.ts` itself, to no avail - getting errors about not being able to resolve modules with the `@/` prefix: `✘ [ERROR] Could not resolve "@/lib/types"`

**Comment by francois2metz** [comment]
Running client side code on Astro can be tricky, here is is working solution for you: https://stackblitz.com/edit/astro-vue-maplibre-gl-nwvouo?file=src%2Fcomponents%2Fapp.astro

**Comment by jtbaker** [comment]
@francois2metz thanks for the response and the cool package, cheers!
