### ISSUE TITLE
Adding official Nuxt support

### ISSUE THREAD

**Issue by Gugustinette** [indoorequal/vue-maplibre-gl#50]
Hi !

I've worked on [Nuxt Leaflet](https://leaflet.nuxtjs.org/) ([git](https://github.com/nuxt-modules/leaflet)) and I'd like to bring a Nuxt Maplibre module to the ecosystem.
As far as I know, this fork is the most maintained and the only one supporting latest Maplibre versions.

Just wanted to know if you were ok with your library being used as the basement for the Nuxt module.

**Comment by francois2metz** [comment]
Hi,

Nice idea to create a nuxt module. Feel free to use this fork!

**Comment by Gugustinette** [comment]
Thanks !

I'll keep this issue up to date with latest informations until the module is released.

**Comment by Gugustinette** [comment]
The module is available here : https://github.com/Gugustinette/nuxt-maplibre

**Comment by francois2metz** [comment]
Thanks! I updated the nuxt section to reference your new package.
