### ISSUE TITLE
MglSymbolLayer application error

### ISSUE THREAD

**Issue by zcrwf** [indoorequal/vue-maplibre-gl#59]
<mgl-vector-source source-id="zcrwf" :url="dataUrl">     
      <mgl-symbol-layer layer-id="my_label" source-layer="cd_location" :layout="layout"
        :filter="filter"></mgl-symbol-layer>
    </mgl-vector-source>

---------------------------------------------------
{
    "message": "Unimplemented type: 4"
}

TypeError: 'caller', 'callee', and 'arguments' properties may not be accessed on strict mode functions or the arguments objects for calls to them
    at Function.invokeGetter (<anonymous>:3:28)

**Comment by francois2metz** [comment]
Hi,
Thanks for reporting an issue. Could you include some details on how to reproduce it, with a small reproduction code for example?

**Comment by zcrwf** [comment]
<mgl-vector-source source-id="zcrwf" :url="dataUrl">
      <mgl-circle-layer layer-id="my" source-layer="cd_location" :paint="paint" :filter="filter" />
      <mgl-symbol-layer layer-id="my_label" source-layer="cd_location" :layout="layout"
        :filter="filter"></mgl-symbol-layer>
    </mgl-vector-source>

**Comment by zcrwf** [comment]
><mgl-map ref="mapRef" :map-style="style" :trackResize=true :center="center" :zoom="zoom" height="100vh"
    :attributionControl=false>

    <mgl-vector-source source-id="zcrwf" :url="dataUrl">
      <mgl-circle-layer layer-id="my" source-layer="cd_location" :paint="paint" :filter="filter" />
      <mgl-symbol-layer layer-id="my_label" source-layer="cd_location" :layout="layout"
        :filter="filter"></mgl-symbol-layer>
    </mgl-vector-source>

**Comment by zcrwf** [comment]
> 您好，感谢您报告问题。您能否包含一些有关如何复制它的详细信息，例如一个小的复制代码？

><mgl-map ref="mapRef" :map-style="style" :trackResize=true :center="center" :zoom="zoom" height="100vh"
    :attributionControl=false>

    <mgl-vector-source source-id="zcrwf" :url="dataUrl">
      <mgl-circle-layer layer-id="my" source-layer="cd_location" :paint="paint" :filter="filter" />
      <mgl-symbol-layer layer-id="my_label" source-layer="cd_location" :layout="layout"
        :filter="filter"></mgl-symbol-layer>
    </mgl-vector-source>

**Comment by francois2metz** [comment]
I'm afraid that I cannot reproduce the issue with the code provided. Could you please provide all the code needed to reproduce it?

**Comment by zcrwf** [comment]
> I'm afraid that I cannot reproduce the issue with the code provided. Could you please provide all the code needed to reproduce it?

Sorry, I found the problem. It's the impact of my glyphs
