### ISSUE TITLE
Unable to use it with typescript

### ISSUE THREAD

**Issue by IceflowRE** [indoorequal/vue-maplibre-gl#71]
Hi iam trying to use your package with the following code, taken from your examples (and added the lang ts)

```vue
<script setup lang="ts">
import { MglMap, MglNavigationControl } from "@indoorequal/vue-maplibre-gl"

const style = "https://api.maptiler.com/maps/streets/style.json?key=cQX2iET1gmOW38bedbUh"
const center = [12.550343, 55.665957]
const zoom = 8
</script>

<template>
    <mgl-map :map-style="style" :center="center" :zoom="zoom" height="500px">
        <mgl-navigation-control />
    </mgl-map>
</template>

<style lang="scss">
@import "maplibre-gl/dist/maplibre-gl.css";
</style>

```

Returning 
```
SyntaxError: The requested module 'http://localhost:3000/node_modules/maplibre-gl/dist/maplibre-gl.js' doesn't provide an export named: 'Map' [vue-router.mjs:3596:20](http://localhost:3000/node_modules/vue-router/dist/vue-router.mjs)
```
If you need any config files i can provide them to you.

**Comment by francois2metz** [comment]
Hi,

Thanks for reporting this issue. 

The following error message is strange:

> SyntaxError: The requested module 'http://localhost:3000/node_modules/maplibre-gl/dist/maplibre-gl.js' doesn't provide an export named: 'Map' [vue-router.mjs:3596:20](http://localhost:3000/node_modules/vue-router/dist/vue-router.mjs)

There is obviously no named export `Map` as it's `MglMap` in your code. Could you try again using the code you provided?

**Comment by IceflowRE** [comment]
I can confirm that this is indeed the code in use and the error message. I also do not use maplibre-gl directly.
Another message is
```
[Vue Router warn]: Unexpected error when starting the router: SyntaxError: The requested module 'http://localhost:3000/node_modules/maplibre-gl/dist/maplibre-gl.js' doesn't provide an export named: 'Map'
```

**Comment by IceflowRE** [comment]
Here is an example project:
https://stackblitz.com/edit/vitejs-vite-65lvgt?file=index.html

**Comment by francois2metz** [comment]
Hi,

I looked at your code. It seems that the vite config is the culprit here. You should remove the `noDiscovery` option of the `optimizeDeps` section in `vite.config.ts`.

**Comment by IceflowRE** [comment]
OMG, thanks!!

I found out that
```
optimizeDeps: {
        noDiscovery: true,
        include: [
            "maplibre-gl",
        ],
    },
```
allows `noDiscovery` still to be used.
