### ISSUE TITLE
Marker with popup "Close popup" does not work

### ISSUE THREAD

**Issue by Sarrasor** [indoorequal/vue-maplibre-gl#76]
Hi. I've tried clicking on the "Close popup" link on the [Marker with popup](https://indoorequal.github.io/vue-maplibre-gl/examples/marker-popup.html) example page and received this error:

![image](https://github.com/user-attachments/assets/00e411cc-0434-4253-b017-8067377684b2)

Any ideas why this happens?

**Comment by francois2metz** [comment]
Hi

Thanks for reporting this issue. Dunno how it ever works, but I released the version 7.6.2 that fix thiss issue.
