### ISSUE TITLE
MglPopup as Tooltip

### ISSUE THREAD

**Issue by jtbaker** [indoorequal/vue-maplibre-gl#78]
I tried to get this functionality working for a bit and couldn't seem to find the right patttern.

In maplibre-gl the pattern I've used for tooltips - popups that display on mouseover and disappear when mousedout is to have a single `Popup` object that I call methods on - chiefly - `.setLngLat, .setDOMContent, .remove(), .addTo(<Map>)`.

I see that the `.remove()` method seems to be exposed through the `.useTemplateRef('popup')` example in the docs - but I can't find how to add the underlying popup back to the map after it is removed. Is there a recommended pattern to follow using idiomatic Vue APIs, or could we get at the underlying `maplibre-gl.Popup` instance it uses to call methods on, similar to how the `useMap()` function provides access the the map?

**Comment by francois2metz** [comment]
Hi,

Thanks for raising this issue. I agree that the remove function that is exposed is not really useful. I released a new version v7.7.0 that may solve it. 
You can now use `v-if` on a popup to show / hide it from the map with native vue tooling. An example is here: https://indoorequal.github.io/vue-maplibre-gl/examples/popup.html
It should be much easier now to use popup as tooltip.

**Comment by jtbaker** [comment]
Yes, just bumped my version and working great now with the `v-if` directive. Thanks for the package, it's nice to have a high level reactive API to some of this stuff!
