### ISSUE TITLE
Error does not provide an export named 'LngLat'

### ISSUE THREAD

**Issue by onmax** [indoorequal/vue-maplibre-gl#84]
## Steps to reproduce

1. Install [Map Libre Nuxt module](https://nuxt.com/modules/nuxt-maplibre) using `npx nuxi@latest module add nuxt-maplibre`
2. Paste the component from the docs:

```vue
<script setup>
const style = 'https://api.maptiler.com/maps/streets/style.json?key=cQX2iET1gmOW38bedbUh'
const center = [-1.559482, 47.21322]
const zoom = 8
</script>

<template>
  <MglMap
    :map-style="style"
    :center="center"
    :zoom="zoom"
  >
    <MglNavigationControl />
  </MglMap>
</template>
```

<details><summary>Error</summary>
<p>

```
vue-maplibre-gl.es.js?v=0272ea42:10 Uncaught (in promise) SyntaxError: The requested module '/_nuxt/@fs/home/maxi/nimiq/map/nuxt/node_modules/.pnpm/maplibre-gl@4.7.1/node_modules/maplibre-gl/dist/maplibre-gl.js?v=0272ea42' does not provide an export named 'LngLat' (at vue-maplibre-gl.es.js?v=0272ea42:10:10)
```

</p>
</details> 

Also this issue I think is related to the issue commented in the new video from [Syntax](https://youtu.be/UAQogFwyna0?t=1360)

**Comment by francois2metz** [comment]
Hi,

Thanks for reporting this issue.
It look like similar to https://github.com/indoorequal/vue-maplibre-gl/issues/71. 
Could you provide a working reproduction code with stackblitz for instance?

**Comment by francois2metz** [comment]
Hi @onmax. Without further details, I'm afraid that I'll close this issue.

**Comment by francois2metz** [comment]
I'm closing it.
