### ISSUE TITLE
Missing emit in props.coordinates watcher of marker.component.ts

### ISSUE THREAD

**Issue by pierredarrieutort** [indoorequal/vue-maplibre-gl#91]
Hey. I've noticed that the `update:coordinates` emit isn't triggered by the watcher of marker.component.ts.

Simple exemple :
In the following exemple the user coordinates are from a computed, so the `coordinates` props are dynamically updated.
```vue
  <MglMarker
    :coordinates="[user.longitude, user.latitude]"
    @update:coordinates="console.log"
  />
```

In the lib, I suggest to add the following :
```ts
watch(
  () => props.coordinates,
  (v) => {
    marker.value?.setLngLat(v)
    emit("update:coordinates", marker.value?.getLngLat())
  },
  { deep: true },
)
```

I've dont made a PR because I don't know if you want to fix this yourself, or simply if you want to enhance this behavior in an other way.

**Comment by pierredarrieutort** [comment]
I want to listen to the coordinates changes to trigger a `flyTo` maplibre method when the coordinates are updated.
The `@update:coordinates` seems to be a good option to avoid to watch the value of coordinates located in my `userStore`.

```vue
<template>
  <MglMarker
    :coordinates="[
      userStore.userLocation.longitude,
      userStore.userLocation.latitude
    ]"
  >
    <template v-slot:marker>
      <div class="user-marker" />
    </template>
  </MglMarker>
</template>

<script setup lang="ts">
  import { MglMarker, useMap } from '@indoorequal/vue-maplibre-gl'
  import { useUserStore } from '@/domains/user/stores/user.store'
  import { computed, watch } from 'vue'
  import type { FlyToOptions } from 'maplibre-gl'

  const props = withDefaults(defineProps<{ cameraBearing?: number }>(), {
    cameraBearing: 0
  })

  const emit = defineEmits(['bearingNeedsUpdate'])

  const userStore = useUserStore()
  const mapInstance = useMap()

 // I want to avoid this watcher by an event from the marker.
  watch(userStore, updateCamera)

  function updateCamera() {
    emit('bearingNeedsUpdate')
    mapInstance.map?.flyTo({
      center: [
        userStore.userLocation.longitude,
        userStore.userLocation.latitude
      ],
      bearing: userStore.userLocation.heading
    })
  }
</script>
```

**Comment by francois2metz** [comment]
I believe it's cleaner to watch the store to update the center of the map. The source of truth is the store. The related code could also be in an upper component.

Still the documentation should at least be updated to document the current behavior.

**Comment by pierredarrieutort** [comment]
I'm agreeing with you. Thanks for your feedback, and thanks to maintain this project, it's really useful for the open source community ! 🔥

**Comment by francois2metz** [comment]
I updated the documentation to avoid this confusion in the future.
